# Generated by Django 5.2.11 on 2026-02-11 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '__first__'),
        ('posts', '__first__'),
        ('tags', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(db_column='faq_id', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='category', max_length=20)),
                ('question', models.CharField(db_column='question', max_length=500)),
                ('answer', models.TextField(db_column='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('expert', models.ForeignKey(blank=True, db_column='expert_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='experts.expert')),
                ('source_post', models.ForeignKey(blank=True, db_column='source_post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='posts.post')),
            ],
            options={
                'db_table': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='FAQTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faq', models.ForeignKey(db_column='faq_id', on_delete=django.db.models.deletion.CASCADE, related_name='faq_tags', to='faq.faq')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='faq_tags', to='tags.tag')),
            ],
            options={
                'db_table': 'FAQTags',
                'unique_together': {('faq', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='tags',
            field=models.ManyToManyField(related_name='faqs', through='faq.FAQTag', to='tags.tag'),
        ),
    ]
